### ISSUE TITLE
is this package still maintained?

### ISSUE THREAD

**Issue by pryorda** [replicatedhq/dockerfilelint#103]

**Comment by fhemberger** [comment]
@fshot @deiga Could you please update the package on npm?

**Comment by nexdrew** [comment]
@fhemberger I think the maintainers/Replicated team mainly uses the [Docker image](https://hub.docker.com/r/replicated/dockerfilelint) for this repo, which is automatically updated when things are merged/pushed to master.

For the Node purists like me 😉 I published version 1.5.0 to npm. Let me know if that helps.

**Comment by fhemberger** [comment]
Thanks!
