### ISSUE TITLE
Empty continuation lines will become errors in a future release

### ISSUE THREAD

**Issue by ArtificialTruth** [replicatedhq/dockerfilelint#137]
Hi,

Very cool tool. An improvement: Check for empty continuation lines, since they will become errors in a future release of docker.

**Comment by svl7** [comment]
@ArtificialTruth I added a pull request that includes this:
https://github.com/replicatedhq/dockerfilelint/pull/147

**Comment by ArtificialTruth** [comment]
Super cool, thank you!
