### ISSUE TITLE
FROM errors with --platform arg

### ISSUE THREAD

**Issue by iggy** [replicatedhq/dockerfilelint#146]
When using the --platform arg to the FROM directive in a Dockerfile, `dockerfilelint` errors saying it should specify a tag.

i.e.

```
Line 7: FROM --platform=$BUILDPLATFORM golang:alpine3.12 as test
Issue  Category      Title                 Description
    1  Clarity       Base Image Missing    Base images should specify a tag to use.
                     Tag
```

I tested just taking out the `--platform=$BUILDPLATFORM` part and it doesn't error any more.

Let me know if you need any more info.

ref:
https://docs.docker.com/engine/reference/builder/#from

**Comment by marccampbell** [comment]
Fixed with #154
