### ISSUE TITLE
Make available as Docker image

### ISSUE THREAD

**Issue by sverhagen** [replicatedhq/dockerfilelint#17]
Make `dockerfilelint` available as public Docker image!

**Comment by marccampbell** [comment]
It's published at https://hub.docker.com/r/replicated/dockerfilelint/

**Comment by sverhagen** [comment]
My bad, thank you!

**Comment by sverhagen** [comment]
12 minutes later, mulled it over at bit... would you agree that `latest` is not a highly useful tag? I embed `dockerfilelint` in my build process, and now different developers could end up with a different version of it on their machine, depending on when they first ran it, relative to when new (`latest`) releases of `dockerfilelint` were pushed.
