### ISSUE TITLE
Repo still actively maintained?

### ISSUE THREAD

**Issue by jokay** [replicatedhq/dockerfilelint#175]
@marccampbell is this repo still actively maintained or do we need to start searching for alternatives?

**Comment by marccampbell** [comment]
@jokay yes! it is.  We've been a little slow in getting releases out, but we use this and are working on it.

We will be looking to bring in additional maintainers to help keep the release cadence up where it needs to be.

**Comment by jokay** [comment]
@marccampbell ok, good to know, will close this issue then :wink:
