### ISSUE TITLE
Skip checks

### ISSUE THREAD

**Issue by sverhagen** [replicatedhq/dockerfilelint#18]
Is it possible to skip selected "rules"? We have a few rules that we find acceptable, despite not being a best practice and it would be nice to silence those.

**Comment by marccampbell** [comment]
We could design a configuration file format (maybe just a simple dot file) to use for configuration.

**Comment by sverhagen** [comment]
We could, but it would not lend itself perfectly for where `dockerfilelint` is used from its Docker image. I would more prefer a command line switch. Looking at the `checks.js` it seems that there's good labels to key off of: `expose_container_port_only`, `expose_port_valid`, `label_format`, etc. So, that could be something like `--ignore=expose_container_port_only,expose_port_valid`. There could potentially be an intermediate level where you'd still get warnings, without the return code of `dockerfilelint` being set to failure. But as it stands now, the notices for failed check are pretty big in your face, so I'd rather being able to silence them altogether.

**Comment by marccampbell** [comment]
This is now supported by creating a .dockerfilelintrc` file in the directory where the Dockerfile is, or in the workdir if running it using stdin.
