### ISSUE TITLE
Invalid certs on website

### ISSUE THREAD

**Issue by lumberj** [replicatedhq/dockerfilelint#22]
Hosted version of this has invalid certs.

<img width="488" alt="screen shot 2016-05-11 at 2 39 35 pm" src="https://cloud.githubusercontent.com/assets/1812196/15197955/42f83188-1789-11e6-83cf-4aa87eacb032.png">

**Comment by marccampbell** [comment]
Thanks @lumberj.  Looks like our letsencrypt auto renewal didn't work.  Updated this and re-deployed the hosted version.  Cert looks valid now.
