### ISSUE TITLE
Site not working on Chrome Canary

### ISSUE THREAD

**Issue by dsifford** [replicatedhq/dockerfilelint#26]
I'm not able to trigger any warnings and the following errors are logged to the console.

![image](https://cloud.githubusercontent.com/assets/5240018/15915178/0bedffdc-2db5-11e6-9e9e-447e5b90a7d6.png)

**Comment by marccampbell** [comment]
This was fixed by with dockerfilelint https://github.com/replicatedhq/dockerfilelint/pull/24 by @nexdrew.  Deployed to fromlatest.io and confirmed.
