### ISSUE TITLE
Add support for HEALTHCHECK command

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/dockerfilelint#28]
Introduced in docker-engine 1.12.  Documentation at https://docs.docker.com/engine/reference/builder/#healthcheck

**Comment by thomasbiddle** [comment]
Would love to see this; currently is being throw as a warning "Invalid Command" in most of my Dockerfiles. This is what's keeping me from implementing it into my CI.

**Comment by boly38** [comment]
@marccampbell could you give a look at #117 and provide a new fresh release ? :)
