### ISSUE TITLE
Image on Docker Hub not up to date

### ISSUE THREAD

**Issue by MrTrustor** [replicatedhq/dockerfilelint#45]
Hello,

The Docker image for this project on the Docker Hub (https://hub.docker.com/r/replicated/dockerfilelint/) is not up to date. In particular, it is missing the ``.dockerfilelintrc`` feature.

Thank you, this is a very cool tool :-)

**Comment by emosbaugh** [comment]
This is resolved in pull requests:
https://github.com/replicatedhq/dockerfilelint/pull/49
https://github.com/replicatedhq/dockerfilelint/pull/50
https://github.com/replicatedhq/dockerfilelint/pull/51
