### ISSUE TITLE
Support Multi Stage Builds

### ISSUE THREAD

**Issue by jaydp17** [replicatedhq/dockerfilelint#74]
Shows error when using [multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/).

The line with second `FROM` shows error.

<img width="844" alt="screen shot 2017-06-29 at 3 15 45 pm" src="https://user-images.githubusercontent.com/1743425/27681822-0ebfa7a2-5cde-11e7-8c3f-b53dab321eb1.png">

**Comment by alexellis** [comment]
Also came here for the same reason. Great tool btw.. very cool.

**Comment by TheYorkshireDev** [comment]
Ditto, any timescales for this guys?

**Comment by nexdrew** [comment]
Apologies for the radio silence! I plan to look into this soon-ish.

**Comment by nexdrew** [comment]
@jaydp17 @alexellis @TheYorkshireDev Opened a PR that allows for more than one `FROM` command, interpreting each as the beginning of a new stage. The PR essentially just makes the linting a little more lenient - I didn't attempt to add any new multi-stage specific checks.

I would love your opinions on if you think this is the right approach or if you have ideas for additional checks that should be made for multi-stage builds.

**Comment by nexdrew** [comment]
Didn't hear back from anyone for over a week, so went ahead and merged #84, which has been published to npm as version 1.4.0. Give it a shot and let me know if it does the trick. Thanks!

**Comment by vipinvkmenon** [comment]
Came for the same Issue. Great tool btw!

**Comment by alexellis** [comment]
Haha, nothing quite like getting a response 18 months after commenting. Better late than never :+1:
