### ISSUE TITLE
License of dockerfilelint unclear

### ISSUE THREAD

**Issue by rcjsuen** [replicatedhq/dockerfilelint#88]
According to the package.json file, the project appears to be under the MIT license.

https://github.com/replicatedhq/dockerfilelint/blob/ad65813edd32e193a5f4534c1082a9b3c7d33ae5/package.json#L24

I'm not sure if this is accurate or just a copy/paste thing. I think a license file should be added to the root of the Git repository to disambiguate the licensing terms and use of this project and its source code.

**Comment by nexdrew** [comment]
Good point. I'll create a PR to add a license file.
